const documentos = [
    {
        id: 1,
        title: 'MONTAGEM E MANUTENÇÃO DE COMPUTADORES',
        description: 'Certificado de Conclusão de Curso',
        codigo: '6564e1a492439b797a244810',
        data: 'Certificado de Conclusão de Curso',
        horas: 260,
        escola: 'Universidade de Santa Cruz do Sul',
        materias: ['Certificado de Conclusão de Curso', 'Certificado de Conclusão de Curso'],
        image: ['https://www.salamineira.com/img/certificado-montagem-e-manutencao-de-computadores-gleiton-aparecido-soares-de-souza.jpeg', 'https://www.salamineira.com/img/fundo-certificado-curso-montagem-e-manutencao-de-computadores-gleiton-aparecido-soares-de-souza.jpeg'],
        informacoes:'',
        pdf: ['https://udemy-certificate.s3.amazonaws.com/image/UC-M78VB7A6.jpg'],
        link: '#',
    },
    {
        id: 2,
        title: 'BLOG AUTOMATICO - COMO GANHAR DINHEIRO COM MARKETING DIGITAL',
        description: 'Certificado de Conclusão de Curso',
        codigo: '6564e1a492439b797a244810',
        data: '22/12/2020',
        horas: 260,
        escola: 'Udemy',
        materias: ['Certificado de Conclusão de Curso', 'Certificado de Conclusão de Curso'],
        image: ['https://udemy-certificate.s3.amazonaws.com/image/UC-868c11ac-7dd7-4203-8355-887eff3bdb65.jpg'],
        informacoes:'',
        pdf: ['https://udemy-certificate.s3.amazonaws.com/image/UC-M78VB7A6.jpg'],
        link: '#',
    },
    {
        id: 3,
        title: 'CURSO COMPLETO DE INSTAGRAM MARKETING',
        description: 'Certificado de Conclusão de Curso',
        codigo: '6564e1a492439b797a244810',
        data: '22/12/2020',
        horas: 7.5,
        escola: 'Udemy',
        materias: ['Certificado de Conclusão de Curso', 'Certificado de Conclusão de Curso'],
        image: ['https://udemy-certificate.s3.amazonaws.com/image/UC-WXJ88BIE.jpg'],
        informacoes:'',
        pdf: ['https://udemy-certificate.s3.amazonaws.com/image/UC-M78VB7A6.jpg'],
        link: '#',
    },
    {
        id: 4,
        title: 'DEV Summit III - FRONTEND MOBILE - GESTÃO DE TI - TRANSFORMAÇÃO DIGITAL',
        description: '',
        codigo: '6564e1a492439b797a244810',
        data: '14/09/2021',
        horas: 20,
        escola: 'INSTITUTO DE GESTÃO E TECNOLOGIA DA INFORMAÇÃO - IGTI',
        materias: [''],
        image: ['https://www.salamineira.com/img/certificado-dev-summit-3-edicao-2021-gleiton-aparecido-soares-de-souza.jpg'],
        informacoes:'',
        pdf: ['https://udemy-certificate.s3.amazonaws.com/image/UC-M78VB7A6.jpg'],
        link: '#',
    },
    {
        id: 0,
        title: 'curso segurança da informação',
        description: '',
        codigo: '6564e1a492439b797a244810',
        data: '01/01/2021',
        horas: 4,
        escola: 'MUPY SYSTEM LTDA',
        materias: [''],
        image: ['https://www.salamineira.com/img/curso-seguranca-da-informacao-gleiton-aparecido-soares-de-souza.png'],
        informacoes:'',
        pdf: ['https://udemy-certificate.s3.amazonaws.com/image/UC-M78VB7A6.jpg'],
        link: '#',
    },
    {
        id: 0,
        title: 'regularização Fundiária - reurb e o desenvolvimento da cidade',
        description: '',
        codigo: '6564e1a492439b797a244810',
        data: '30/06/2021',
        horas: 5,
        escola: 'CORI-MG - FORUM DE REGULARIZAÇÃO FUNDIÁRIA',
        materias: [''],
        image: ['https://www.salamineira.com/img/Certificado-regularizacao-fundiaria-lagoa-dos-patos-mg.png'],
        informacoes:'',
        pdf: ['https://udemy-certificate.s3.amazonaws.com/image/UC-M78VB7A6.jpg'],
        link: '#',
    },
    {
        id: 0,
        title: 'FORMAÇÃO DE PREGOEIRO e equipe de apoio - BNC',
        description: '',
        codigo: '6564e1a492439b797a244810',
        data: '16/06/2021',
        horas: 16,
        escola: 'BNC - Bolsa Nacional de Compras',
        materias: [''],
        informacoes:'',
        image: ['https://www.salamineira.com/img/certificado-pregoeiro-pregoeiro-em-lagoa-dos-patos-mg.png', 'https://www.salamineira.com/img/certificado-pregoeiro-pregoeiro-em-lagoa-dos-patos-mg-2.png'],
        pdf: ['https://udemy-certificate.s3.amazonaws.com/image/UC-M78VB7A6.jpg'],
        link: '#',
    },
    {
        id: 0,
        title: 'COMO APARECER NO GOOGLE',
        description: '',
        codigo: '6564e1a492439b797a244810',
        pdf: ['https://udemy-certificate.s3.amazonaws.com/image/UC-M78VB7A6.jpg'],
        data: '24/0/2018',
        horas: 8,
        escola: 'UDEMY',
        materias: [''],
        informacoes:'',
        image: ['https://udemy-certificate.s3.amazonaws.com/image/UC-M78VB7A6.jpg'],
        link: '#',
    },
    {
        id: 0,
        title: 'TRADE MARKETING',
        codigo: '6564e1a492439b797a244810',
        pdf: '/certificados/trade-marketing.pdf',
        image: ['https://udemy-certificate.s3.amazonaws.com/image/UC-M78VB7A6.jpg'],
        inicio: '24/03/2022',
        fim: '24/03/2022',
        horas: '4',
        escola: 'SEBRAE CURSOS',
        pontuacao: '10', 
        informacoes: '',
        link: '#',
    },
    {
        id: 0,
        title: 'LIDERANÇA: COMO DESENVOLVER TIMES DE ALTA PERFORMANCE',
        codigo: '66f91e847529ee25e5b6b85e',
        pdf: '/certificados/lideranca-como-desenvolver-times-de-alta-performance.pdf',
        image: ['https://udemy-certificate.s3.amazonaws.com/image/UC-M78VB7A6.jpg'],
        inicio: '28/09/2024',
        fim: '29/09/2024',
        horas: '2',
        escola: 'SEBRAE CURSOS',
        pontuacao: '10', 
        informacoes: '',
        link: ['https://udemy-certificate.s3.amazonaws.com/image/UC-M78VB7A6.jpg'],
    },
    {
        id: 0,
        title: 'CURSO DE MONTAGEM E MANUTENÇÃO DE COMPUTADORES',
        codigo: '',
        pdf: '/certificados/trade-marketing',
        image: ['https://udemy-certificate.s3.amazonaws.com/image/UC-M78VB7A6.jpg'],
        inicio: '18/04/2011',
        fim: '18/07/2011',
        horas: '260',
        escola: 'IPR - UNIVERSIDADE SANTA CRUZ DO SUL',
        pontuacao: '70', 
        informacoes: '',
        link: ['https://udemy-certificate.s3.amazonaws.com/image/UC-M78VB7A6.jpg'],
    },
    {
        id: 0,
        title: 'LIDERANÇA',
        codigo: '6564e1a492439b797a244810',
        pdf: '/certificados/trade-marketing',
        image: ['https://udemy-certificate.s3.amazonaws.com/image/UC-M78VB7A6.jpg'],
        inicio: '24/03/2022',
        fim: '24/03/2022',
        horas: '4',
        escola: 'SEBRAE CURSOS',
        pontuacao: '10', 
        informacoes: '',       
        link: '#',
    },
    {
        id: 0,
        title: 'COMO APARECER NO GOOGLE',
        description: '',
        codigo: '6564e1a492439b797a244810',
        pdf: ['https://udemy-certificate.s3.amazonaws.com/image/UC-M78VB7A6.jpg'],
        data: '24/0/2018',
        horas: 8,
        escola: 'UDEMY',
        materias: [''],
        image: ['https://udemy-certificate.s3.amazonaws.com/image/UC-M78VB7A6.jpg'],
        link: '#',
    },
    {
        id: 0,
        title: 'WORKSHOP Metodologias Ágeis',
        description: '',
        codigo: 'e65ciyu6j7',
        data: '12/05/2022',
        horas: 1,
        inicio: '12/05/2022',
        fim: '12/05/2022',
        escola: 'SENAC',
        materias: [''],
        image: ['/certificados/metodologia-senac-gleiton-2.png', '/certificados/metodologia-senac-gleiton-1.png'],
        pontuacao: '',
        informacoes: '',
        pdf: ['/certificados/pdf/certificado_Gleiton_Aparecido_Soares_de_Souza.pdf'],
        link: 'https://www.mg.senac.br/faculdade/Paginas/consulta-ficeac.aspx',
    },
    {
        id: 0,
        title: '',
        description: '',
        codigo: '6564e1a492439b797a244810',
        data: '',
        horas: 0,
        inicio: '',
        fim: '',
        escola: '',
        materias: [''],
        image: [''],
        pontuacao: '',
        informacoes: '',
        pdf: ['https://udemy-certificate.s3.amazonaws.com/image/UC-M78VB7A6.jpg'],
        link: '#',
    },
    {
        id: 0,
        title: '',
        description: '',
        codigo: '6564e1a492439b797a244810',
        data: '',
        horas: 0,
        inicio: '',
        fim: '',
        escola: '',
        materias: [''],
        image: [''],
        pontuacao: '',
        informacoes: '',
        pdf: ['https://udemy-certificate.s3.amazonaws.com/image/UC-M78VB7A6.jpg'],
        link: '#',
    },
    {
        id: 0,
        title: '',
        description: '',
        codigo: '6564e1a492439b797a244810',
        data: '',
        horas: 0,
        inicio: '',
        fim: '',
        escola: '',
        materias: [''],
        image: [''],
        pontuacao: '',
        informacoes: '',
        pdf: ['https://udemy-certificate.s3.amazonaws.com/image/UC-M78VB7A6.jpg'],
        link: '#',
    }
]
export default documentos;