const documentos = [
    {
        id: 1,
        title: 'MONTAGEM E MANUTENÇÃO DE COMPUTADORES',
        description: 'Certificado de Conclusão de Curso',
        data: 'Certificado de Conclusão de Curso',
        horas: 260,
        escola: 'Universidade de Santa Cruz do Sul',
        materias: ['Certificado de Conclusão de Curso', 'Certificado de Conclusão de Curso'],
        image: ['https://www.salamineira.com/img/certificado-montagem-e-manutencao-de-computadores-gleiton-aparecido-soares-de-souza.jpeg', 'https://www.salamineira.com/img/fundo-certificado-curso-montagem-e-manutencao-de-computadores-gleiton-aparecido-soares-de-souza.jpeg'],
        link: '#',
    },
    {
        id: 2,
        title: 'BLOG AUTOMATICO - COMO GANHAR DINHEIRO COM MARKETING DIGITAL',
        description: 'Certificado de Conclusão de Curso',
        data: '22/12/2020',
        horas: 260,
        escola: 'Udemy',
        materias: ['Certificado de Conclusão de Curso', 'Certificado de Conclusão de Curso'],
        image: ['https://udemy-certificate.s3.amazonaws.com/image/UC-868c11ac-7dd7-4203-8355-887eff3bdb65.jpg'],
        link: '#',
    },
    {
        id: 3,
        title: 'CURSO COMPLETO DE INSTAGRAM MARKETING',
        description: 'Certificado de Conclusão de Curso',
        data: '22/12/2020',
        horas: 7.5,
        escola: 'Udemy',
        materias: ['Certificado de Conclusão de Curso', 'Certificado de Conclusão de Curso'],
        image: ['https://udemy-certificate.s3.amazonaws.com/image/UC-WXJ88BIE.jpg'],
        link: '#',
    },
    {
        id: 4,
        title: 'DEV Summit III - FRONTEND MOBILE - GESTÃO DE TI - TRANSFORMAÇÃO DIGITAL',
        description: '',
        data: '14/09/2021',
        horas: 20,
        escola: 'INSTITUTO DE GESTÃO E TECNOLOGIA DA INFORMAÇÃO - IGTI',
        materias: [''],
        image: ['https://www.salamineira.com/img/certificado-dev-summit-3-edicao-2021-gleiton-aparecido-soares-de-souza.jpg'],
        link: '#',
    },
    {
        id: 0,
        title: 'curso segurança da informação',
        description: '',
        data: '01/01/2021',
        horas: 4,
        escola: 'MUPY SYSTEM LTDA',
        materias: [''],
        image: ['https://www.salamineira.com/img/curso-seguranca-da-informacao-gleiton-aparecido-soares-de-souza.png'],
        link: '#',
    },
    {
        id: 0,
        title: 'regularização Fundiária - reurb e o desenvolvimento da cidade',
        description: '',
        data: '30/06/2021',
        horas: 5,
        escola: 'CORI-MG - FORUM DE REGULARIZAÇÃO FUNDIÁRIA',
        materias: [''],
        image: ['https://www.salamineira.com/img/Certificado-regularizacao-fundiaria-lagoa-dos-patos-mg.png'],
        link: '#',
    },
    {
        id: 0,
        title: 'FORMAÇÃO DE PREGOEIRO e equipe de apoio - BNC',
        description: '',
        data: '16/06/2021',
        horas: 16,
        escola: 'BNC - Bolsa Nacional de Compras',
        materias: [''],
        image: ['https://www.salamineira.com/img/certificado-pregoeiro-pregoeiro-em-lagoa-dos-patos-mg.png', 'https://www.salamineira.com/img/certificado-pregoeiro-pregoeiro-em-lagoa-dos-patos-mg-2.png'],
        link: '#',
    },
    {
        id: 0,
        title: 'COMO APARECER NO GOOGLE',
        description: '',
        data: '24/0/2018',
        horas: 8,
        escola: 'UDEMY',
        materias: [''],
        image: ['https://udemy-certificate.s3.amazonaws.com/image/UC-M78VB7A6.jpg'],
        link: '#',
    },
    {
        id: 0,
        title: 'COMO APARECER NO GOOGLE',
        description: '',
        data: '24/0/2018',
        horas: 8,
        escola: 'UDEMY',
        materias: [''],
        image: ['https://udemy-certificate.s3.amazonaws.com/image/UC-M78VB7A6.jpg'],
        link: '#',
    },
    {
        id: 0,
        title: '',
        description: '',
        data: '',
        horas: 0,
        escola: '',
        materias: [''],
        image: [''],
        link: '#',
    }
]
export default documentos;